version: "2.3"
services:
  opendatacam:
    restart: always
    runtime: nvidia
    image: opendatacam/opendatacam:v3.0.2-desktop
    privileged: true
    volumes:
      - './config.json:/var/local/opendatacam/config.json'
      - './yolov4-tiny.weights:/var/local/darknet/yolov4-tiny.weights'
    ports:
      - "8083:8080"
      - "8073:8070"
      - "8093:8090"
  mongo:
    image: mongo
    restart: always
    ports:
      - "27020:27017"
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: